default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: michelada_development

test:
  <<: *default
  host: localhost
  database: michelada_test